# Generated by Django 5.1.2 on 2024-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
